// SPDX-License-Identifier: FSL-1.1-Apache-2.0
//
// Package notifyprofiles stores notification profiles: the per-team (or
// org-wide) bundles of behaviour + channels that decide how an alert (or
// an unacknowledged error) is delivered. Each alert resolves to exactly
// one profile, most-specific-first:
//
//	integration's assigned profile -> owning team's default profile
//	                               -> the org-wide default profile.
//
// A profile carries its channels, a grouping mode (per_check /
// per_integration), and a re-notify interval. This package replaces the
// flat notifyroutes scopes.
package notifyprofiles

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Grouping modes.
const (
	GroupingPerCheck       = "per_check"
	GroupingPerIntegration = "per_integration"
)

// ErrNotFound is returned when a profile doesn't exist (or isn't visible).
var ErrNotFound = errors.New("notification profile not found")

// Profile is a notification profile + its channel ids.
type Profile struct {
	ID              uuid.UUID   `json:"id"`
	OrganizationID  uuid.UUID   `json:"organization_id"`
	GroupID         *uuid.UUID  `json:"group_id,omitempty"` // nil = org-wide
	Name            string      `json:"name"`
	Grouping        string      `json:"grouping"`
	RenotifyMinutes int         `json:"renotify_minutes"`
	IsDefault       bool        `json:"is_default"`
	ChannelIDs      []uuid.UUID `json:"channel_ids"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

type Store struct{ pool *pgxpool.Pool }

func NewStore(pool *pgxpool.Pool) *Store { return &Store{pool: pool} }

const profileCols = `id, organization_id, group_id, name, grouping, renotify_minutes, is_default, created_at, updated_at`

func scanProfile(row pgx.Row) (Profile, error) {
	var p Profile
	var grp uuid.NullUUID
	if err := row.Scan(&p.ID, &p.OrganizationID, &grp, &p.Name, &p.Grouping, &p.RenotifyMinutes, &p.IsDefault, &p.CreatedAt, &p.UpdatedAt); err != nil {
		return Profile{}, err
	}
	if grp.Valid {
		id := grp.UUID
		p.GroupID = &id
	}
	p.ChannelIDs = []uuid.UUID{}
	return p, nil
}

// List returns every profile in the org with channels attached.
func (s *Store) List(ctx context.Context, orgID uuid.UUID) ([]Profile, error) {
	rows, err := s.pool.Query(ctx, `SELECT `+profileCols+`
		FROM notification_profiles WHERE organization_id = $1
		ORDER BY group_id NULLS FIRST, name`, orgID)
	if err != nil {
		return nil, fmt.Errorf("notifyprofiles: list: %w", err)
	}
	defer rows.Close()
	var out []Profile
	for rows.Next() {
		p, err := scanProfile(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, p)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return s.attachChannels(ctx, orgID, out)
}

// Get returns one profile with channels.
func (s *Store) Get(ctx context.Context, orgID, id uuid.UUID) (Profile, error) {
	row := s.pool.QueryRow(ctx, `SELECT `+profileCols+`
		FROM notification_profiles WHERE organization_id = $1 AND id = $2`, orgID, id)
	p, err := scanProfile(row)
	if errors.Is(err, pgx.ErrNoRows) {
		return Profile{}, ErrNotFound
	}
	if err != nil {
		return Profile{}, err
	}
	ch, err := s.channelIDs(ctx, id)
	if err != nil {
		return Profile{}, err
	}
	p.ChannelIDs = ch
	return p, nil
}

// Create inserts a profile (id generated by the caller).
func (s *Store) Create(ctx context.Context, p Profile) (Profile, error) {
	if p.Grouping == "" {
		p.Grouping = GroupingPerCheck
	}
	row := s.pool.QueryRow(ctx, `
		INSERT INTO notification_profiles (id, organization_id, group_id, name, grouping, renotify_minutes, is_default)
		VALUES ($1, $2, $3, $4, $5, $6, $7)
		RETURNING `+profileCols, p.ID, p.OrganizationID, p.GroupID, p.Name, p.Grouping, p.RenotifyMinutes, p.IsDefault)
	created, err := scanProfile(row)
	if err != nil {
		return Profile{}, fmt.Errorf("notifyprofiles: create: %w", err)
	}
	if p.IsDefault {
		if err := s.clearOtherDefaults(ctx, p.OrganizationID, p.GroupID, created.ID); err != nil {
			return Profile{}, err
		}
	}
	return created, nil
}

// Update changes a profile's mutable fields (name/grouping/renotify/default).
func (s *Store) Update(ctx context.Context, orgID uuid.UUID, p Profile) (Profile, error) {
	if p.Grouping == "" {
		p.Grouping = GroupingPerCheck
	}
	row := s.pool.QueryRow(ctx, `
		UPDATE notification_profiles
		SET name = $3, grouping = $4, renotify_minutes = $5, is_default = $6, updated_at = now()
		WHERE organization_id = $1 AND id = $2
		RETURNING `+profileCols, orgID, p.ID, p.Name, p.Grouping, p.RenotifyMinutes, p.IsDefault)
	updated, err := scanProfile(row)
	if errors.Is(err, pgx.ErrNoRows) {
		return Profile{}, ErrNotFound
	}
	if err != nil {
		return Profile{}, fmt.Errorf("notifyprofiles: update: %w", err)
	}
	if p.IsDefault {
		if err := s.clearOtherDefaults(ctx, orgID, updated.GroupID, updated.ID); err != nil {
			return Profile{}, err
		}
	}
	return updated, nil
}

// Delete removes a profile (its channel links + integration assignments
// cascade / null out via FK).
func (s *Store) Delete(ctx context.Context, orgID, id uuid.UUID) error {
	tag, err := s.pool.Exec(ctx, `DELETE FROM notification_profiles WHERE organization_id = $1 AND id = $2`, orgID, id)
	if err != nil {
		return fmt.Errorf("notifyprofiles: delete: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

// SetChannels replaces a profile's channel set.
func (s *Store) SetChannels(ctx context.Context, profileID uuid.UUID, channelIDs []uuid.UUID) error {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer tx.Rollback(ctx)
	if _, err := tx.Exec(ctx, `DELETE FROM notification_profile_channels WHERE profile_id = $1`, profileID); err != nil {
		return fmt.Errorf("notifyprofiles: clear channels: %w", err)
	}
	for _, ch := range dedupe(channelIDs) {
		if _, err := tx.Exec(ctx,
			`INSERT INTO notification_profile_channels (profile_id, channel_id) VALUES ($1, $2)`, profileID, ch); err != nil {
			return fmt.Errorf("notifyprofiles: insert channel: %w", err)
		}
	}
	return tx.Commit(ctx)
}

// clearOtherDefaults makes profileID the only default in its scope (team
// or org-wide).
func (s *Store) clearOtherDefaults(ctx context.Context, orgID uuid.UUID, groupID *uuid.UUID, keep uuid.UUID) error {
	var q string
	var args []any
	if groupID == nil {
		q = `UPDATE notification_profiles SET is_default = FALSE, updated_at = now()
			WHERE organization_id = $1 AND group_id IS NULL AND id <> $2 AND is_default`
		args = []any{orgID, keep}
	} else {
		q = `UPDATE notification_profiles SET is_default = FALSE, updated_at = now()
			WHERE organization_id = $1 AND group_id = $2 AND id <> $3 AND is_default`
		args = []any{orgID, *groupID, keep}
	}
	_, err := s.pool.Exec(ctx, q, args...)
	return err
}

// EnsureOrgDefault creates an empty org-wide default profile the first
// time the cell boots, so resolution always has a final fallback.
func (s *Store) EnsureOrgDefault(ctx context.Context, orgID uuid.UUID) error {
	var n int
	if err := s.pool.QueryRow(ctx,
		`SELECT count(*) FROM notification_profiles WHERE organization_id = $1 AND group_id IS NULL`, orgID).Scan(&n); err != nil {
		return err
	}
	if n > 0 {
		return nil
	}
	_, err := s.pool.Exec(ctx, `
		INSERT INTO notification_profiles (id, organization_id, group_id, name, grouping, renotify_minutes, is_default)
		VALUES (gen_random_uuid(), $1, NULL, 'Default', 'per_check', 0, TRUE)`, orgID)
	return err
}

// channelIDs loads one profile's channels.
func (s *Store) channelIDs(ctx context.Context, profileID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := s.pool.Query(ctx, `SELECT channel_id FROM notification_profile_channels WHERE profile_id = $1`, profileID)
	if err != nil {
		return nil, fmt.Errorf("notifyprofiles: channel ids: %w", err)
	}
	defer rows.Close()
	out := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		out = append(out, id)
	}
	return out, rows.Err()
}

// attachChannels bulk-loads channels for a set of profiles.
func (s *Store) attachChannels(ctx context.Context, orgID uuid.UUID, profiles []Profile) ([]Profile, error) {
	if len(profiles) == 0 {
		return profiles, nil
	}
	byID := make(map[uuid.UUID]int, len(profiles))
	for i := range profiles {
		byID[profiles[i].ID] = i
	}
	rows, err := s.pool.Query(ctx, `
		SELECT pc.profile_id, pc.channel_id
		FROM notification_profile_channels pc
		JOIN notification_profiles p ON p.id = pc.profile_id
		WHERE p.organization_id = $1`, orgID)
	if err != nil {
		return nil, fmt.Errorf("notifyprofiles: attach channels: %w", err)
	}
	defer rows.Close()
	for rows.Next() {
		var pid, cid uuid.UUID
		if err := rows.Scan(&pid, &cid); err != nil {
			return nil, err
		}
		if i, ok := byID[pid]; ok {
			profiles[i].ChannelIDs = append(profiles[i].ChannelIDs, cid)
		}
	}
	return profiles, rows.Err()
}

func dedupe(ids []uuid.UUID) []uuid.UUID {
	seen := map[uuid.UUID]struct{}{}
	out := make([]uuid.UUID, 0, len(ids))
	for _, id := range ids {
		if _, ok := seen[id]; ok {
			continue
		}
		seen[id] = struct{}{}
		out = append(out, id)
	}
	return out
}
