{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- $ctx := dict "root" . "component" "cell-alerting" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cell.componentName" $ctx }}
  labels: {{- include "cell.labels" $ctx | nindent 4 }}
spec:
  replicas: {{ .Values.cellAlerting.replicaCount }}
  selector:
    matchLabels: {{- include "cell.selectorLabels" $ctx | nindent 6 }}
  template:
    metadata:
      labels: {{- include "cell.selectorLabels" $ctx | nindent 8 }}
    spec:
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: cell-alerting
          image: "{{ .Values.cellAlerting.image.repository }}:{{ .Values.cellAlerting.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          securityContext: {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          env:
            {{- include "cell.dbEnv" . | nindent 12 }}
          resources: {{- toYaml .Values.cellAlerting.resources | nindent 12 }}
